### ISSUE TITLE
[Feat] 7주차 실습 과제

### ISSUE THREAD

**Issue by Johyerin** [AND-SOPT-iOS/JoHyerin#19]
## 🔥 Issue 내용
7주차 실습 과제

## ✅ To-do
- [ ] 2개 이상의 뷰모델을 구현해보아야 합니다.
- [ ] Grid / List 등을 사용해보아야 합니다.
- [ ] 최대한 컴포넌트를 분리하세요.
